#!/usr/bin/python

import argparse
import os
import sys

from datetime import datetime

def ensure_directory_exists(dir_structure):
    # Make sure that the directory structure for our entry exists.
    if not os.path.isdir(dir_structure):
        os.makedirs(dir_structure)

    return True

def check_entry_exists(target_file):
    # Check if an entry already exists or not.
    return os.path.isfile(target_file)

def generate_datestamp(entry_date):
    # Create a valid datetime object based on the inputted string.
    datestamp = datetime.strptime(entry_date, "%Y/%m/%d")

    return datestamp

def create_entry(entry_name,
                 entry_date):
    #
    #   Create a diary entry.
    #
    # Place it in a directory such as YYYY/MM/DD/entry-name.md

    directory_structure = entry_date.strftime('%Y/%m/%d')

    ensure_directory_exists(directory_structure)

    target_file = "%s/%s.md" % (directory_structure, entry_name)

    if check_entry_exists(target_file):
        raise argparse.ArgumentTypeError(
                "Entry with filename '%s' exists." % target_file)

    entry_file = open(target_file, 'w')

    entry_file.write("%s\n" % entry_name)

    # Put in a heading into our file in Markdown.
    # TODO: Find a better way to perform this.
    for x in range(0, len(entry_name)):
        entry_file.write("=")

def delete_entry(entry_name,
                 entry_date):
    # Delete an entry and it's the last one for that date,
    # delete the directory.
    directory_structure = entry_date.strftime('%Y/%m/%d')
    target_file = "%s/%s.md" % (directory_structure, entry_name)

    if not check_entry_exists(target_file):
        raise argparse.ArgumentTypeError(
                "Entry with filename '%s' does not exist." % target_file)

    os.unlink(target_file)

if __name__ == "__main__":
    # First of all: parse our arguments and verify them.
    parser = argparse.ArgumentParser(
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description="Manage diary entries with Git.")
    parser.add_argument(
            'action',
            help="Action to perform on entry."
            )
    parser.add_argument(
            '--name',
            help="Name of entry to perform action on.",
            )
    parser.add_argument(
            '--date',
            help="Date of entry to perform action on (Format: YYYY/MM/DD).",
            default=datetime.now(),
            )

    args = parser.parse_args()

    if args.action not in ("create", "remove", "edit"):
        raise argparse.ArgumentTypeError("Invalid action.")

    if args.name is None:
        raise argparse.ArgumentTypeError("No entry name specified.")

    date = args.date

    if isinstance(args.date, str):
        date = generate_datestamp(args.date)

    if args.action in "create":
        create_entry(args.name, date)

    if args.action in "remove":
        delete_entry(args.name, date)
