#!/usr/bin/python

import argparse
import os
import sys
import time

if __name__ == "__main__":
    # Parse our arguments first of all.
    parser = argparse.ArgumentParser(
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description="Manage diary entries with Git.")
    parser.add_argument(
            'action',
            help="Action to perform on entry."
            )
    parser.add_argument(
            '--name',
            help="Name of entry to perform action on.",
            dest="name"
            )

    args = parser.parse_args()

    if args.action not in ("create", "remove", "edit"):
        raise argparse.ArgumentTypeError("Invalid action.")

    if args.action in "create":
        print "Creating entry '%s'." % args.name
